name: Create qualification reports

on:
  workflow_dispatch:

jobs:
  create-reports:
    runs-on: ubuntu-latest
    steps: 
    - name: Info 
      run: echo "Please branch from create-reports to use this action"
  
